# coding: utf-8

"""
    Chat Telegram Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatt_client.api.support_api import SupportApi


class TestSupportApi(unittest.TestCase):
    """SupportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SupportApi()

    def tearDown(self) -> None:
        pass

    def test_send_message_telegram_support_users_user_id_setting_setting_id_post(self) -> None:
        """Test case for send_message_telegram_support_users_user_id_setting_setting_id_post

        Send Message Telegram
        """
        pass


if __name__ == '__main__':
    unittest.main()
