# coding: utf-8

"""
    Chat Telegram Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatt_client.api.setting_api import SettingApi


class TestSettingApi(unittest.TestCase):
    """SettingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingApi()

    def tearDown(self) -> None:
        pass

    def test_auth_telegram_by_phone_setting_auth_code_post(self) -> None:
        """Test case for auth_telegram_by_phone_setting_auth_code_post

        Auth Telegram By Phone
        """
        pass

    def test_auth_telegram_by_phone_setting_auth_post(self) -> None:
        """Test case for auth_telegram_by_phone_setting_auth_post

        Auth Telegram By Phone
        """
        pass


if __name__ == '__main__':
    unittest.main()
