# coding: utf-8

"""
    Chat Telegram Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatt_client.models.type_message_enum import TypeMessageEnum

class TestTypeMessageEnum(unittest.TestCase):
    """TypeMessageEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeMessageEnum(self):
        """Test TypeMessageEnum"""
        # inst = TypeMessageEnum()

if __name__ == '__main__':
    unittest.main()
