# coding: utf-8

# flake8: noqa
"""
    Chat Telegram Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from chatt_client.models.health_check_details_schema import HealthCheckDetailsSchema
from chatt_client.models.health_check_response import HealthCheckResponse
from chatt_client.models.message_schema import MessageSchema
from chatt_client.models.message_schema_sent import MessageSchemaSent
from chatt_client.models.service_error_pydantic import ServiceErrorPydantic
from chatt_client.models.status_database import StatusDatabase
from chatt_client.models.status_redis import StatusRedis
from chatt_client.models.type_error_enum import TypeErrorEnum
from chatt_client.models.type_message_enum import TypeMessageEnum
